# Generated by Django 5.0.7 on 2024-07-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField()),
                ("date", models.DateField()),
                ("company", models.CharField(max_length=50)),
                ("categories", models.CharField(max_length=150)),
                ("url", models.URLField()),
            ],
        ),
    ]
