# Generated by Django 5.0.7 on 2024-07-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawlers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobad",
            name="workplace",
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
