# Generated by Django 5.0.7 on 2024-08-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawlers", "0002_jobad_workplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="jobad",
            name="categories",
        ),
        migrations.AddField(
            model_name="jobad",
            name="categories",
            field=models.ManyToManyField(to="crawlers.category"),
        ),
    ]
