# Generated by Django 5.0.7 on 2024-08-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawlers", "0003_category_remove_jobad_categories_jobad_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
