# Generated by Django 5.0.7 on 2024-08-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawlers", "0004_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobad",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
