# Generated by Django 5.0.7 on 2024-08-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawlers", "0005_jobad_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="jobad",
            name="company",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="jobad",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="jobad",
            name="workplace",
            field=models.CharField(max_length=100),
        ),
    ]
