# Generated by Django 5.0.7 on 2024-08-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0006_alter_category_name_alter_jobad_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobad',
            name='technologies',
            field=models.ManyToManyField(to='crawlers.technology'),
        ),
    ]
