# Generated by Django 5.0.7 on 2024-08-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0007_technology_jobad_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobad',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crawlers.workplace'),
        ),
    ]
