# Generated by Django 5.0.7 on 2024-08-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0008_workplace_alter_jobad_workplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('categories', models.CharField(blank=True, null=True)),
                ('techstack', models.CharField(blank=True, null=True)),
                ('workplace', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
