# Generated by Django 5.0.7 on 2024-08-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0009_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='techstack',
            new_name='technologies',
        ),
    ]
