# Generated by Django 5.0.7 on 2024-08-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0010_rename_techstack_search_technologies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='workplace',
            new_name='workplaces',
        ),
    ]
