# Generated by Django 5.0.7 on 2024-08-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0011_rename_workplace_search_workplaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='user',
            field=models.BigIntegerField(),
        ),
    ]
