# Generated by Django 5.0.7 on 2024-08-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0012_alter_search_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobad',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
