# Generated by Django 5.0.7 on 2024-08-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0013_alter_jobad_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('bio', models.CharField(blank=True, null=True)),
                ('education', models.CharField(blank=True, null=True)),
                ('work_experience', models.CharField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, null=True)),
                ('other', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
