# Generated by Django 5.0.7 on 2024-08-28 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0015_alter_profile_bio_alter_profile_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('job_ad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crawlers.jobad')),
            ],
        ),
    ]
